package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.BbsBD;
import com.srct.ril.poas.dao.pojo.BbsBDExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BbsBDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int countByExample(BbsBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int deleteByExample(BbsBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int insert(BbsBD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int insertSelective(BbsBD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    List<BbsBD> selectByExample(BbsBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    BbsBD selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BbsBD record, @Param("example") BbsBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BbsBD record, @Param("example") BbsBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BbsBD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BbsBD record);
}