package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.BbsGC;
import com.srct.ril.poas.dao.pojo.BbsGCExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BbsGCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int countByExample(BbsGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int deleteByExample(BbsGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int insert(BbsGC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int insertSelective(BbsGC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    List<BbsGC> selectByExample(BbsGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    BbsGC selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BbsGC record, @Param("example") BbsGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BbsGC record, @Param("example") BbsGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BbsGC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BbsGC record);
}