package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.BbsJF;
import com.srct.ril.poas.dao.pojo.BbsJFExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BbsJFMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int countByExample(BbsJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int deleteByExample(BbsJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int insert(BbsJF record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int insertSelective(BbsJF record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    List<BbsJF> selectByExample(BbsJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    BbsJF selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BbsJF record, @Param("example") BbsJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BbsJF record, @Param("example") BbsJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BbsJF record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BbsJF record);
}