package com.srct.ril.poas.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srct.ril.poas.dao.pojo.DaoAMZ;
import com.srct.ril.poas.dao.pojo.DaoAMZExample;

public interface DaoAMZMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int countByExample(DaoAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int deleteByExample(DaoAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int insert(DaoAMZ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int insertSelective(DaoAMZ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    List<DaoAMZ> selectByExample(DaoAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    DaoAMZ selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DaoAMZ record, @Param("example") DaoAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DaoAMZ record, @Param("example") DaoAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DaoAMZ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DaoAMZ record);
}