package com.srct.ril.poas.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srct.ril.poas.dao.pojo.DaoBD;
import com.srct.ril.poas.dao.pojo.DaoBDExample;

public interface DaoBDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int countByExample(DaoBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int deleteByExample(DaoBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int insert(DaoBD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int insertSelective(DaoBD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    List<DaoBD> selectByExample(DaoBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    DaoBD selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DaoBD record, @Param("example") DaoBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DaoBD record, @Param("example") DaoBDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DaoBD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DaoBD record);
}