package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.DaoGC;
import com.srct.ril.poas.dao.pojo.DaoGCExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DaoGCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int countByExample(DaoGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int deleteByExample(DaoGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int insert(DaoGC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int insertSelective(DaoGC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    List<DaoGC> selectByExample(DaoGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    DaoGC selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DaoGC record, @Param("example") DaoGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DaoGC record, @Param("example") DaoGCExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DaoGC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GC
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DaoGC record);
}