package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.DaoJD;
import com.srct.ril.poas.dao.pojo.DaoJDExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DaoJDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int countByExample(DaoJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int deleteByExample(DaoJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int insert(DaoJD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int insertSelective(DaoJD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    List<DaoJD> selectByExample(DaoJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    DaoJD selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DaoJD record, @Param("example") DaoJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DaoJD record, @Param("example") DaoJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DaoJD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DaoJD record);
}