package com.srct.ril.poas.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srct.ril.poas.dao.pojo.DaoJF;
import com.srct.ril.poas.dao.pojo.DaoJFExample;

public interface DaoJFMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int countByExample(DaoJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int deleteByExample(DaoJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int insert(DaoJF record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int insertSelective(DaoJF record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    List<DaoJF> selectByExample(DaoJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    DaoJF selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DaoJF record, @Param("example") DaoJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DaoJF record, @Param("example") DaoJFExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DaoJF record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JF
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DaoJF record);
}