package com.srct.ril.poas.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.srct.ril.poas.dao.pojo.DaoTB;
import com.srct.ril.poas.dao.pojo.DaoTBExample;

public interface DaoTBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int countByExample(DaoTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int deleteByExample(DaoTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int insert(DaoTB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int insertSelective(DaoTB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    List<DaoTB> selectByExample(DaoTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    DaoTB selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DaoTB record, @Param("example") DaoTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DaoTB record, @Param("example") DaoTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DaoTB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DaoTB record);
}