package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.Keyword;
import com.srct.ril.poas.dao.pojo.KeywordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KeywordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    int countByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    int deleteByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    int insert(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    int insertSelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    List<Keyword> selectByExample(KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    Keyword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Keyword record, @Param("example") KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Keyword record, @Param("example") KeywordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Keyword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table keyword_
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Keyword record);
}