package com.srct.ril.poas.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.srct.ril.poas.dao.pojo.ModelMap;
import com.srct.ril.poas.dao.pojo.ModelMapExample;

public interface ModelMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    int countByExample(ModelMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    int deleteByExample(ModelMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    int insert(ModelMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    int insertSelective(ModelMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    List<ModelMap> selectByExample(ModelMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    ModelMap selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ModelMap record, @Param("example") ModelMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ModelMap record, @Param("example") ModelMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ModelMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modelmap_
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ModelMap record);
}