package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.SourceMap;
import com.srct.ril.poas.dao.pojo.SourceMapExample;
import java.util.List;

public interface SourceMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    int insert(SourceMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    int insertSelective(SourceMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    List<SourceMap> selectByExample(SourceMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    SourceMap selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SourceMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SourceMap record);
}