package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.StoreTM;
import com.srct.ril.poas.dao.pojo.StoreTMExample;
import com.srct.ril.poas.dao.pojo.StoreTMWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreTMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int countByExample(StoreTMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int deleteByExample(StoreTMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int insert(StoreTMWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int insertSelective(StoreTMWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    List<StoreTMWithBLOBs> selectByExampleWithBLOBs(StoreTMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    List<StoreTM> selectByExample(StoreTMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    StoreTMWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StoreTMWithBLOBs record, @Param("example") StoreTMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") StoreTMWithBLOBs record, @Param("example") StoreTMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StoreTM record, @Param("example") StoreTMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StoreTMWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(StoreTMWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StoreTM record);
}