package com.srct.ril.poas.dao.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.srct.ril.poas.dao.pojo.StoreJD;
import com.srct.ril.poas.dao.pojo.StoreJDExample;

public interface StoreJDMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int countByExample(StoreJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int deleteByExample(StoreJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int insert(StoreJD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int insertSelective(StoreJD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    List<StoreJD> selectByExample(StoreJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    StoreJD selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StoreJD record, @Param("example") StoreJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StoreJD record, @Param("example") StoreJDExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StoreJD record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JD
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StoreJD record);
}