package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.StoreTB;
import com.srct.ril.poas.dao.pojo.StoreTBExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreTBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int countByExample(StoreTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int deleteByExample(StoreTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int insert(StoreTB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int insertSelective(StoreTB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    List<StoreTB> selectByExample(StoreTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    StoreTB selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StoreTB record, @Param("example") StoreTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StoreTB record, @Param("example") StoreTBExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StoreTB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StoreTB record);
}