package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.StoreAMZ;
import com.srct.ril.poas.dao.pojo.StoreAMZExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StoreAMZMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int countByExample(StoreAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int deleteByExample(StoreAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int insert(StoreAMZ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int insertSelective(StoreAMZ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    List<StoreAMZ> selectByExample(StoreAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    StoreAMZ selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") StoreAMZ record, @Param("example") StoreAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") StoreAMZ record, @Param("example") StoreAMZExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StoreAMZ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AMZ
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StoreAMZ record);
}