package com.srct.ril.poas.dao.mapper;

import com.srct.ril.poas.dao.pojo.UrlMap;
import com.srct.ril.poas.dao.pojo.UrlMapExample;
import java.util.List;

public interface UrlMapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urlmap_
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urlmap_
     *
     * @mbggenerated
     */
    int insert(UrlMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urlmap_
     *
     * @mbggenerated
     */
    int insertSelective(UrlMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urlmap_
     *
     * @mbggenerated
     */
    List<UrlMap> selectByExample(UrlMapExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urlmap_
     *
     * @mbggenerated
     */
    UrlMap selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urlmap_
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UrlMap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table urlmap_
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UrlMap record);
}