package com.srct.ril.poas.dao.pojo;

public class DaoBD extends StoreBbsPojoBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD.firstcomment
     *
     * @mbggenerated
     */
    private String firstcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD.replynum
     *
     * @mbggenerated
     */
    private String replynum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD.sentiment
     *
     * @mbggenerated
     */
    private Integer sentiment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BD.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD.id
     *
     * @return the value of BD.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD.id
     *
     * @param id the value for BD.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD.title
     *
     * @return the value of BD.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD.title
     *
     * @param title the value for BD.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD.firstcomment
     *
     * @return the value of BD.firstcomment
     *
     * @mbggenerated
     */
    public String getFirstcomment() {
        return firstcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD.firstcomment
     *
     * @param firstcomment the value for BD.firstcomment
     *
     * @mbggenerated
     */
    public void setFirstcomment(String firstcomment) {
        this.firstcomment = firstcomment == null ? null : firstcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD.replynum
     *
     * @return the value of BD.replynum
     *
     * @mbggenerated
     */
    public String getReplynum() {
        return replynum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD.replynum
     *
     * @param replynum the value for BD.replynum
     *
     * @mbggenerated
     */
    public void setReplynum(String replynum) {
        this.replynum = replynum == null ? null : replynum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD.date
     *
     * @return the value of BD.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD.date
     *
     * @param date the value for BD.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD.link
     *
     * @return the value of BD.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD.link
     *
     * @param link the value for BD.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD.sentiment
     *
     * @return the value of BD.sentiment
     *
     * @mbggenerated
     */
    public Integer getSentiment() {
        return sentiment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD.sentiment
     *
     * @param sentiment the value for BD.sentiment
     *
     * @mbggenerated
     */
    public void setSentiment(Integer sentiment) {
        this.sentiment = sentiment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BD.category
     *
     * @return the value of BD.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BD.category
     *
     * @param category the value for BD.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }
}