package com.srct.ril.poas.dao.pojo;

public class DaoJD extends StoreBbsPojoBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.userlevel
     *
     * @mbggenerated
     */
    private String userlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.firstcomment
     *
     * @mbggenerated
     */
    private String firstcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.star
     *
     * @mbggenerated
     */
    private String star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.client
     *
     * @mbggenerated
     */
    private String client;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.referenceName
     *
     * @mbggenerated
     */
    private String referencename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.sentiment
     *
     * @mbggenerated
     */
    private Integer sentiment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JD.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.id
     *
     * @return the value of JD.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.id
     *
     * @param id the value for JD.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.username
     *
     * @return the value of JD.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.username
     *
     * @param username the value for JD.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.userlevel
     *
     * @return the value of JD.userlevel
     *
     * @mbggenerated
     */
    public String getUserlevel() {
        return userlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.userlevel
     *
     * @param userlevel the value for JD.userlevel
     *
     * @mbggenerated
     */
    public void setUserlevel(String userlevel) {
        this.userlevel = userlevel == null ? null : userlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.firstcomment
     *
     * @return the value of JD.firstcomment
     *
     * @mbggenerated
     */
    public String getFirstcomment() {
        return firstcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.firstcomment
     *
     * @param firstcomment the value for JD.firstcomment
     *
     * @mbggenerated
     */
    public void setFirstcomment(String firstcomment) {
        this.firstcomment = firstcomment == null ? null : firstcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.star
     *
     * @return the value of JD.star
     *
     * @mbggenerated
     */
    public String getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.star
     *
     * @param star the value for JD.star
     *
     * @mbggenerated
     */
    public void setStar(String star) {
        this.star = star == null ? null : star.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.date
     *
     * @return the value of JD.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.date
     *
     * @param date the value for JD.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.client
     *
     * @return the value of JD.client
     *
     * @mbggenerated
     */
    public String getClient() {
        return client;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.client
     *
     * @param client the value for JD.client
     *
     * @mbggenerated
     */
    public void setClient(String client) {
        this.client = client == null ? null : client.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.color
     *
     * @return the value of JD.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.color
     *
     * @param color the value for JD.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.size
     *
     * @return the value of JD.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.size
     *
     * @param size the value for JD.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.referenceName
     *
     * @return the value of JD.referenceName
     *
     * @mbggenerated
     */
    public String getReferencename() {
        return referencename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.referenceName
     *
     * @param referencename the value for JD.referenceName
     *
     * @mbggenerated
     */
    public void setReferencename(String referencename) {
        this.referencename = referencename == null ? null : referencename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.link
     *
     * @return the value of JD.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.link
     *
     * @param link the value for JD.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.sentiment
     *
     * @return the value of JD.sentiment
     *
     * @mbggenerated
     */
    public Integer getSentiment() {
        return sentiment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.sentiment
     *
     * @param sentiment the value for JD.sentiment
     *
     * @mbggenerated
     */
    public void setSentiment(Integer sentiment) {
        this.sentiment = sentiment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JD.category
     *
     * @return the value of JD.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JD.category
     *
     * @param category the value for JD.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }
}