package com.srct.ril.poas.dao.pojo;

public class ModelMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modelmap_.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modelmap_.model_name
     *
     * @mbggenerated
     */
    private String modelName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modelmap_.id
     *
     * @return the value of modelmap_.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modelmap_.id
     *
     * @param id the value for modelmap_.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modelmap_.model_name
     *
     * @return the value of modelmap_.model_name
     *
     * @mbggenerated
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modelmap_.model_name
     *
     * @param modelName the value for modelmap_.model_name
     *
     * @mbggenerated
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }
}