package com.srct.ril.poas.dao.pojo;

public class SourceMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcemap_.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcemap_.source_en
     *
     * @mbggenerated
     */
    private String sourceEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sourcemap_.source_cn
     *
     * @mbggenerated
     */
    private String sourceCn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcemap_.id
     *
     * @return the value of sourcemap_.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sourcemap_.id
     *
     * @param id the value for sourcemap_.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcemap_.source_en
     *
     * @return the value of sourcemap_.source_en
     *
     * @mbggenerated
     */
    public String getSourceEn() {
        return sourceEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sourcemap_.source_en
     *
     * @param sourceEn the value for sourcemap_.source_en
     *
     * @mbggenerated
     */
    public void setSourceEn(String sourceEn) {
        this.sourceEn = sourceEn == null ? null : sourceEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sourcemap_.source_cn
     *
     * @return the value of sourcemap_.source_cn
     *
     * @mbggenerated
     */
    public String getSourceCn() {
        return sourceCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sourcemap_.source_cn
     *
     * @param sourceCn the value for sourcemap_.source_cn
     *
     * @mbggenerated
     */
    public void setSourceCn(String sourceCn) {
        this.sourceCn = sourceCn == null ? null : sourceCn.trim();
    }
}