package com.srct.ril.poas.dao.pojo;

import java.util.ArrayList;
import java.util.List;

public class SourceMapExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public SourceMapExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSourceEnIsNull() {
            addCriterion("source_en is null");
            return (Criteria) this;
        }

        public Criteria andSourceEnIsNotNull() {
            addCriterion("source_en is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEnEqualTo(String value) {
            addCriterion("source_en =", value, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnNotEqualTo(String value) {
            addCriterion("source_en <>", value, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnGreaterThan(String value) {
            addCriterion("source_en >", value, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnGreaterThanOrEqualTo(String value) {
            addCriterion("source_en >=", value, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnLessThan(String value) {
            addCriterion("source_en <", value, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnLessThanOrEqualTo(String value) {
            addCriterion("source_en <=", value, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnLike(String value) {
            addCriterion("source_en like", value, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnNotLike(String value) {
            addCriterion("source_en not like", value, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnIn(List<String> values) {
            addCriterion("source_en in", values, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnNotIn(List<String> values) {
            addCriterion("source_en not in", values, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnBetween(String value1, String value2) {
            addCriterion("source_en between", value1, value2, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceEnNotBetween(String value1, String value2) {
            addCriterion("source_en not between", value1, value2, "sourceEn");
            return (Criteria) this;
        }

        public Criteria andSourceCnIsNull() {
            addCriterion("source_cn is null");
            return (Criteria) this;
        }

        public Criteria andSourceCnIsNotNull() {
            addCriterion("source_cn is not null");
            return (Criteria) this;
        }

        public Criteria andSourceCnEqualTo(String value) {
            addCriterion("source_cn =", value, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnNotEqualTo(String value) {
            addCriterion("source_cn <>", value, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnGreaterThan(String value) {
            addCriterion("source_cn >", value, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnGreaterThanOrEqualTo(String value) {
            addCriterion("source_cn >=", value, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnLessThan(String value) {
            addCriterion("source_cn <", value, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnLessThanOrEqualTo(String value) {
            addCriterion("source_cn <=", value, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnLike(String value) {
            addCriterion("source_cn like", value, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnNotLike(String value) {
            addCriterion("source_cn not like", value, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnIn(List<String> values) {
            addCriterion("source_cn in", values, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnNotIn(List<String> values) {
            addCriterion("source_cn not in", values, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnBetween(String value1, String value2) {
            addCriterion("source_cn between", value1, value2, "sourceCn");
            return (Criteria) this;
        }

        public Criteria andSourceCnNotBetween(String value1, String value2) {
            addCriterion("source_cn not between", value1, value2, "sourceCn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sourcemap_
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sourcemap_
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}