package com.srct.ril.poas.dao.pojo;

public class StoreTM {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.firstcomment
     *
     * @mbggenerated
     */
    private String firstcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.appendComment
     *
     * @mbggenerated
     */
    private String appendcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.appenddate
     *
     * @mbggenerated
     */
    private String appenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.reply
     *
     * @mbggenerated
     */
    private String reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.referenceName
     *
     * @mbggenerated
     */
    private String referencename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.sentiment
     *
     * @mbggenerated
     */
    private Integer sentiment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.category
     *
     * @mbggenerated
     */
    private Integer category;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.id
     *
     * @return the value of TM.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.id
     *
     * @param id the value for TM.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.username
     *
     * @return the value of TM.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.username
     *
     * @param username the value for TM.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.firstcomment
     *
     * @return the value of TM.firstcomment
     *
     * @mbggenerated
     */
    public String getFirstcomment() {
        return firstcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.firstcomment
     *
     * @param firstcomment the value for TM.firstcomment
     *
     * @mbggenerated
     */
    public void setFirstcomment(String firstcomment) {
        this.firstcomment = firstcomment == null ? null : firstcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.date
     *
     * @return the value of TM.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.date
     *
     * @param date the value for TM.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.appendComment
     *
     * @return the value of TM.appendComment
     *
     * @mbggenerated
     */
    public String getAppendcomment() {
        return appendcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.appendComment
     *
     * @param appendcomment the value for TM.appendComment
     *
     * @mbggenerated
     */
    public void setAppendcomment(String appendcomment) {
        this.appendcomment = appendcomment == null ? null : appendcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.appenddate
     *
     * @return the value of TM.appenddate
     *
     * @mbggenerated
     */
    public String getAppenddate() {
        return appenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.appenddate
     *
     * @param appenddate the value for TM.appenddate
     *
     * @mbggenerated
     */
    public void setAppenddate(String appenddate) {
        this.appenddate = appenddate == null ? null : appenddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.reply
     *
     * @return the value of TM.reply
     *
     * @mbggenerated
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.reply
     *
     * @param reply the value for TM.reply
     *
     * @mbggenerated
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.referenceName
     *
     * @return the value of TM.referenceName
     *
     * @mbggenerated
     */
    public String getReferencename() {
        return referencename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.referenceName
     *
     * @param referencename the value for TM.referenceName
     *
     * @mbggenerated
     */
    public void setReferencename(String referencename) {
        this.referencename = referencename == null ? null : referencename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.link
     *
     * @return the value of TM.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.link
     *
     * @param link the value for TM.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.sentiment
     *
     * @return the value of TM.sentiment
     *
     * @mbggenerated
     */
    public Integer getSentiment() {
        return sentiment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.sentiment
     *
     * @param sentiment the value for TM.sentiment
     *
     * @mbggenerated
     */
    public void setSentiment(Integer sentiment) {
        this.sentiment = sentiment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.category
     *
     * @return the value of TM.category
     *
     * @mbggenerated
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.category
     *
     * @param category the value for TM.category
     *
     * @mbggenerated
     */
    public void setCategory(Integer category) {
        this.category = category;
    }
}