package com.srct.ril.poas.dao.pojo;

public class StoreTMWithBLOBs extends StoreTM {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.firstcomment
     *
     * @mbggenerated
     */
    private String firstcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.appendComment
     *
     * @mbggenerated
     */
    private String appendcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TM.reply
     *
     * @mbggenerated
     */
    private String reply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.firstcomment
     *
     * @return the value of TM.firstcomment
     *
     * @mbggenerated
     */
    public String getFirstcomment() {
        return firstcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.firstcomment
     *
     * @param firstcomment the value for TM.firstcomment
     *
     * @mbggenerated
     */
    public void setFirstcomment(String firstcomment) {
        this.firstcomment = firstcomment == null ? null : firstcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.appendComment
     *
     * @return the value of TM.appendComment
     *
     * @mbggenerated
     */
    public String getAppendcomment() {
        return appendcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.appendComment
     *
     * @param appendcomment the value for TM.appendComment
     *
     * @mbggenerated
     */
    public void setAppendcomment(String appendcomment) {
        this.appendcomment = appendcomment == null ? null : appendcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TM.reply
     *
     * @return the value of TM.reply
     *
     * @mbggenerated
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TM.reply
     *
     * @param reply the value for TM.reply
     *
     * @mbggenerated
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }
}