package com.srct.ril.poas.dao.pojo;

public class StoreTB {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.firstcomment
     *
     * @mbggenerated
     */
    private String firstcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.appendComment
     *
     * @mbggenerated
     */
    private String appendcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.appenddate
     *
     * @mbggenerated
     */
    private String appenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.reply
     *
     * @mbggenerated
     */
    private String reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.referenceName
     *
     * @mbggenerated
     */
    private String referencename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.id
     *
     * @return the value of TB.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.id
     *
     * @param id the value for TB.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.username
     *
     * @return the value of TB.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.username
     *
     * @param username the value for TB.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.firstcomment
     *
     * @return the value of TB.firstcomment
     *
     * @mbggenerated
     */
    public String getFirstcomment() {
        return firstcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.firstcomment
     *
     * @param firstcomment the value for TB.firstcomment
     *
     * @mbggenerated
     */
    public void setFirstcomment(String firstcomment) {
        this.firstcomment = firstcomment == null ? null : firstcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.date
     *
     * @return the value of TB.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.date
     *
     * @param date the value for TB.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.appendComment
     *
     * @return the value of TB.appendComment
     *
     * @mbggenerated
     */
    public String getAppendcomment() {
        return appendcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.appendComment
     *
     * @param appendcomment the value for TB.appendComment
     *
     * @mbggenerated
     */
    public void setAppendcomment(String appendcomment) {
        this.appendcomment = appendcomment == null ? null : appendcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.appenddate
     *
     * @return the value of TB.appenddate
     *
     * @mbggenerated
     */
    public String getAppenddate() {
        return appenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.appenddate
     *
     * @param appenddate the value for TB.appenddate
     *
     * @mbggenerated
     */
    public void setAppenddate(String appenddate) {
        this.appenddate = appenddate == null ? null : appenddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.reply
     *
     * @return the value of TB.reply
     *
     * @mbggenerated
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.reply
     *
     * @param reply the value for TB.reply
     *
     * @mbggenerated
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.referenceName
     *
     * @return the value of TB.referenceName
     *
     * @mbggenerated
     */
    public String getReferencename() {
        return referencename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.referenceName
     *
     * @param referencename the value for TB.referenceName
     *
     * @mbggenerated
     */
    public void setReferencename(String referencename) {
        this.referencename = referencename == null ? null : referencename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.link
     *
     * @return the value of TB.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.link
     *
     * @param link the value for TB.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }
}