package com.srct.ril.poas.dao.pojo;

public class StoreTBWithBLOBs extends StoreTB {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.firstcomment
     *
     * @mbggenerated
     */
    private String firstcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.appendComment
     *
     * @mbggenerated
     */
    private String appendcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB.reply
     *
     * @mbggenerated
     */
    private String reply;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.firstcomment
     *
     * @return the value of TB.firstcomment
     *
     * @mbggenerated
     */
    public String getFirstcomment() {
        return firstcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.firstcomment
     *
     * @param firstcomment the value for TB.firstcomment
     *
     * @mbggenerated
     */
    public void setFirstcomment(String firstcomment) {
        this.firstcomment = firstcomment == null ? null : firstcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.appendComment
     *
     * @return the value of TB.appendComment
     *
     * @mbggenerated
     */
    public String getAppendcomment() {
        return appendcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.appendComment
     *
     * @param appendcomment the value for TB.appendComment
     *
     * @mbggenerated
     */
    public void setAppendcomment(String appendcomment) {
        this.appendcomment = appendcomment == null ? null : appendcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB.reply
     *
     * @return the value of TB.reply
     *
     * @mbggenerated
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB.reply
     *
     * @param reply the value for TB.reply
     *
     * @mbggenerated
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }
}