package com.srct.ril.poas.dao.pojo;

public class StoreAMZ {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMZ.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMZ.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMZ.firstcomment
     *
     * @mbggenerated
     */
    private String firstcomment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMZ.star
     *
     * @mbggenerated
     */
    private String star;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMZ.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMZ.referenceName
     *
     * @mbggenerated
     */
    private String referencename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AMZ.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMZ.id
     *
     * @return the value of AMZ.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMZ.id
     *
     * @param id the value for AMZ.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMZ.title
     *
     * @return the value of AMZ.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMZ.title
     *
     * @param title the value for AMZ.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMZ.firstcomment
     *
     * @return the value of AMZ.firstcomment
     *
     * @mbggenerated
     */
    public String getFirstcomment() {
        return firstcomment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMZ.firstcomment
     *
     * @param firstcomment the value for AMZ.firstcomment
     *
     * @mbggenerated
     */
    public void setFirstcomment(String firstcomment) {
        this.firstcomment = firstcomment == null ? null : firstcomment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMZ.star
     *
     * @return the value of AMZ.star
     *
     * @mbggenerated
     */
    public String getStar() {
        return star;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMZ.star
     *
     * @param star the value for AMZ.star
     *
     * @mbggenerated
     */
    public void setStar(String star) {
        this.star = star == null ? null : star.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMZ.date
     *
     * @return the value of AMZ.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMZ.date
     *
     * @param date the value for AMZ.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMZ.referenceName
     *
     * @return the value of AMZ.referenceName
     *
     * @mbggenerated
     */
    public String getReferencename() {
        return referencename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMZ.referenceName
     *
     * @param referencename the value for AMZ.referenceName
     *
     * @mbggenerated
     */
    public void setReferencename(String referencename) {
        this.referencename = referencename == null ? null : referencename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AMZ.link
     *
     * @return the value of AMZ.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AMZ.link
     *
     * @param link the value for AMZ.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }
}