package com.srct.ril.poas.dao.pojo;

public class UrlMap {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urlmap_.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urlmap_.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urlmap_.model_id
     *
     * @mbggenerated
     */
    private Integer modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urlmap_.source_id
     *
     * @mbggenerated
     */
    private Integer sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column urlmap_.last_fetch_time
     *
     * @mbggenerated
     */
    private String lastFetchTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urlmap_.id
     *
     * @return the value of urlmap_.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urlmap_.id
     *
     * @param id the value for urlmap_.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urlmap_.url
     *
     * @return the value of urlmap_.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urlmap_.url
     *
     * @param url the value for urlmap_.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urlmap_.model_id
     *
     * @return the value of urlmap_.model_id
     *
     * @mbggenerated
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urlmap_.model_id
     *
     * @param modelId the value for urlmap_.model_id
     *
     * @mbggenerated
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urlmap_.source_id
     *
     * @return the value of urlmap_.source_id
     *
     * @mbggenerated
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urlmap_.source_id
     *
     * @param sourceId the value for urlmap_.source_id
     *
     * @mbggenerated
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column urlmap_.last_fetch_time
     *
     * @return the value of urlmap_.last_fetch_time
     *
     * @mbggenerated
     */
    public String getLastFetchTime() {
        return lastFetchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column urlmap_.last_fetch_time
     *
     * @param lastFetchTime the value for urlmap_.last_fetch_time
     *
     * @mbggenerated
     */
    public void setLastFetchTime(String lastFetchTime) {
        this.lastFetchTime = lastFetchTime == null ? null : lastFetchTime.trim();
    }
}